name = "Vanilla Performance"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b7fc89567072f55bbaba1e79259c34cd49beb73df6ac0d72ee643b1b8998cedd"

[versions]
minecraft = "1.20.1"
quilt = "0.20.2"
