name = "Vanilla Performance"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c1a6a2bf81a38fed6d9731cf9f129e68566ab82af50084b10ac9a1b95649cee2"

[versions]
minecraft = "1.20.1"
quilt = "0.20.2"
