name = "Vanilla Performance"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8b2b033ff0bfd413e6520ccb4851f3ec35afa1e879ce4ba57e09f7200d413ef2"

[versions]
minecraft = "1.20.1"
quilt = "0.20.2"
